version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    command: "npm start"